<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-danborghi/blob/main/AtividadeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [2]:
import numpy as np
a1D = np.zeros(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.

In [3]:
import numpy as np
a1D = np.ones(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
(10,)



### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [4]:
import numpy as np
a1D = np.arange(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)


### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).


In [5]:
import numpy as np
a2D = np.arange(9).reshape((3,3))
print(a2D)
print(a2D.dtype)
print(a2D.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
int64
(3, 3)


# 5. Índices não zero (fácil)

In [6]:

import numpy as np

v = np.array([1, 2, 0, 0, 4, 0])
idx = np.nonzero(v)[0]
print(idx)


[0 1 4]


# 6. Linspace (fácil)

In [7]:

import numpy as np

lin = np.linspace(0, 1, 12)
print(lin)


[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


# 7. Identidade 5×5 (fácil)


In [8]:

import numpy as np

I = np.eye(5)
print(I)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 8. Aleatórios 3×3×3 (fácil)



In [9]:

import numpy as np

rng = np.random.default_rng(42)
arr_3 = rng.random((3, 3, 3))
print(arr_3)


[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


# 9. Min/Max (fácil)


In [10]:

import numpy as np

rng = np.random.default_rng()
A = rng.random((10, 10))
print(A.min(), A.max())


0.004201978013798513 0.9953168636954565


# 10. Padronização 1D (fácil)

In [11]:

import numpy as np

x = [1, 2, 3, 4, 5]
x = np.array(x, dtype=float)
x_std = (x - x.mean()) / x.std()
print(x_std, x_std.mean(), x_std.std())


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356] 0.0 0.9999999999999999


# 11. Conversão de tipos (fácil)

In [12]:

import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
a_f32 = a.astype(np.float32)
a_i64 = a_f32.astype(np.int64)
print(a.dtype, a_f32.dtype, a_i64.dtype)


int32 float32 int64


# 12. Clipping (fácil)

In [13]:

import numpy as np

a = np.array([2, 5, 7, 1, 9])
clipped = np.clip(a, 0, 5)
print(clipped)


[2 5 5 1 5]


# 13. Inversão (fácil) — sem usar [::-1]

In [14]:

import numpy as np

v = np.arange(10)
v_inv = np.flip(v)
print(v_inv)


[9 8 7 6 5 4 3 2 1 0]


# 14. Empilhamento (fácil)


In [15]:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h = np.hstack((a, b))
v = np.vstack((a, b))
print(h)
print(v)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# 15. Diagonal (fácil)


In [16]:

import numpy as np

M = np.diag(np.full(4, 5))
print(M)


[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


# 16. Somas por eixo (fácil)


In [17]:

import numpy as np

A = np.arange(12).reshape(3, 4)
soma_linhas = A.sum(axis=1)
soma_colunas = A.sum(axis=0)
print("linhas:", soma_linhas)
print("colunas:", soma_colunas)


linhas: [ 6 22 38]
colunas: [12 15 18 21]


# 17. Frequências inteiras (fácil)



In [18]:

import numpy as np

rng = np.random.default_rng(42)
vals = rng.integers(0, 10, size=100)
freq = np.bincount(vals, minlength=10)
print(freq)


[ 9  9  6  9 15  7 11 15 12  7]


# 18. Slicing com passo (fácil)


In [19]:

import numpy as np

v = np.arange(20)
sel = v[1::3]
print(sel)


[ 1  4  7 10 13 16 19]


# 19. Máscara booleana (fácil)


In [20]:

import numpy as np

v = np.arange(20)
mask = (v % 2 == 0)
pares = v[mask]
print(mask)
print(pares)


[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 0  2  4  6  8 10 12 14 16 18]


# 20. Lista de listas → array (fácil)


In [21]:

import numpy as np

L = [[1, 2, 3], [4, 5, 6]]
arr = np.array(L)
print(arr)
print("shape:", arr.shape, "dtype:", arr.dtype)


[[1 2 3]
 [4 5 6]]
shape: (2, 3) dtype: int64


# 21. Datas básicas (fácil)


In [22]:

import numpy as np

datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(datas)


['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


# 22. Centralizar colunas (fácil)


In [23]:

import numpy as np

A = np.array([[1., 2., 3.],
              [4., 5., 6.]])
A_centered = A - A.mean(axis=0, keepdims=True)
print(A_centered)


[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


# 23. Produto elemento-a-elemento vs. escalar (fácil)


In [24]:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

elem = a * b
dot1 = np.dot(a, b)
dot2 = a @ b
print(elem, dot1, dot2)


[ 4 10 18] 32 32


# 24. Troca de colunas (fácil)



In [25]:

import numpy as np

A = np.arange(12).reshape(3, 4)
tmp = A[:, 0].copy()
A[:, 0] = A[:, 2]
A[:, 2] = tmp
print(A)



[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]



### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.


In [26]:
import numpy as np

A = np.arange(6).reshape(2, 3)
f = A.flatten()
r = A.ravel()

print("A original:\n", A)
print("shares_memory(A, f)?", np.shares_memory(A, f))
print("shares_memory(A, r)?", np.shares_memory(A, r))

r[0] = 999
print("\nApós r[0]=999:")
print("A:\n", A)
print("f (cópia, não muda):\n", f)


A original:
 [[0 1 2]
 [3 4 5]]
shares_memory(A, f)? False
shares_memory(A, r)? True

Após r[0]=999:
A:
 [[999   1   2]
 [  3   4   5]]
f (cópia, não muda):
 [0 1 2 3 4 5]


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [27]:
import numpy as np

board = (np.indices((8, 8)).sum(axis=0) % 2).astype(int)
print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [28]:
import numpy as np

x = np.arange(-5, 6)
y = np.where(x < 0, 0, x)
print("x:", x)
print("y:", y)


x: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
y: [0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [29]:
import numpy as np

rng = np.random.default_rng(42)
samples = rng.random(1_000_000)
m = samples.mean()
err_abs = abs(m - 0.5)
print("média:", m, "erro absoluto:", err_abs)


média: 0.5000264761740889 erro absoluto: 2.6476174088907456e-05


### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).


In [30]:
import numpy as np

a = np.array([1, 2, 3])[:, None]
b = np.array([10, 20, 30, 40])[None, :]
S = a + b
print(S)


[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [31]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

def conv1d_valid(s, k):
    s = np.asarray(s)
    k = np.asarray(k)
    kf = np.flip(k)
    windows = sliding_window_view(s, window_shape=k.size)
    return (windows * kf).sum(axis=1)

s = np.array([1, 2, 3, 4, 5])
k = np.array([1, 0, -1])
print(conv1d_valid(s, k))

[2 2 2]


### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.

In [32]:
import numpy as np

rng = np.random.default_rng(42)
A = rng.normal(size=(5, 4))

col_min = A.min(axis=0, keepdims=True)
col_max = A.max(axis=0, keepdims=True)
den = col_max - col_min
den_safe = np.where(den == 0, 1, den)
A_minmax = (A - col_min) / den_safe

print("A:\n", A)
print("\nNormalizado [0,1] por coluna:\n", A_minmax)


A:
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826   0.8784503  -0.04992591]]

Normalizado [0,1] por coluna:
 [[0.97239672 0.10792507 0.82842728 1.        ]
 [0.         0.         0.         0.30171831]
 [0.83379849 0.18487353 1.         0.9095635 ]
 [0.86950517 1.         0.45195332 0.        ]
 [1.         0.14130813 0.99873905 0.44968376]]


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.

In [33]:
import numpy as np

A = np.array([[3, 9],
              [1, 4],
              [2, 5]])
order = np.argsort(A[:, 1])
A_sorted = A[order]
print(A_sorted)


[[1 4]
 [2 5]
 [3 9]]


### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [34]:
import numpy as np

x = np.array([3, 1, 2, 3, 2, 3, 1])
vals, idx_first, counts = np.unique(x, return_index=True, return_counts=True)
print("valores únicos (ordenados):", vals)
print("contagens:", counts)
print("índice da 1ª ocorrência (no x original):", idx_first)


valores únicos (ordenados): [1 2 3]
contagens: [2 2 3]
índice da 1ª ocorrência (no x original): [1 2 0]


### 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

In [35]:
import numpy as np

P = np.array([[0.0, 0.0],
              [1.0, 0.0],
              [1.0, 1.0],
              [2.0, 2.0]])

sq_norms = (P**2).sum(axis=1, keepdims=True)
D2 = sq_norms - 2 * (P @ P.T) + sq_norms.T
D2 = np.maximum(D2, 0.0)
D = np.sqrt(D2)
print(D)


[[0.         1.         1.41421356 2.82842712]
 [1.         0.         1.         2.23606798]
 [1.41421356 1.         0.         1.41421356]
 [2.82842712 2.23606798 1.41421356 0.        ]]


### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [36]:
import numpy as np

rng = np.random.default_rng(42)
X = rng.normal(size=(1000, 3))

cov = np.cov(X, rowvar=False)
corr = np.corrcoef(X, rowvar=False)
print("cov:\n", cov)
print("\ncorrelação:\n", corr)


cov:
 [[ 1.02807939  0.003405   -0.03028368]
 [ 0.003405    0.99691425  0.06347086]
 [-0.03028368  0.06347086  1.0227042 ]]

correlação:
 [[ 1.          0.00336338 -0.02953387]
 [ 0.00336338  1.          0.06285943]
 [-0.02953387  0.06285943  1.        ]]


### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.

In [37]:
import numpy as np

y = np.array([2, 0, 1, 2])
n_classes = y.max() + 1
one_hot = np.eye(n_classes, dtype=int)[y]
print(one_hot)


[[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
