<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-danborghi/blob/main/AtividadeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Vetor de zeros  _(fácil)_

Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

In [ ]:
import numpy as np
a1D = np.zeros(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


### 2. Vetor de uns  _(fácil)_

Crie um array 1D com 10 uns e transforme-o em float64.

In [ ]:
import numpy as np
a1D = np.ones(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
(10,)



### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [ ]:
import numpy as np
a1D = np.arange(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)


### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).


In [ ]:
import numpy as np
a2D = np.arange(9).reshape((3,3))
print(a2D)
print(a2D.dtype)
print(a2D.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
int64
(3, 3)


# 5. Índices não zero (fácil)

In [ ]:

import numpy as np

v = np.array([1, 2, 0, 0, 4, 0])
idx = np.nonzero(v)[0]
print(idx)


[0 1 4]


# 6. Linspace (fácil)

In [ ]:

import numpy as np

lin = np.linspace(0, 1, 12)
print(lin)


[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


# 7. Identidade 5×5 (fácil)


In [ ]:

import numpy as np

I = np.eye(5)
print(I)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 8. Aleatórios 3×3×3 (fácil)



In [ ]:

import numpy as np

rng = np.random.default_rng(42)
arr_3 = rng.random((3, 3, 3))
print(arr_3)


[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


# 9. Min/Max (fácil)


In [ ]:

import numpy as np

rng = np.random.default_rng()
A = rng.random((10, 10))
print(A.min(), A.max())


0.00037478579081140495 0.9967016872878377


# 10. Padronização 1D (fácil)

In [ ]:

import numpy as np

x = [1, 2, 3, 4, 5]
x = np.array(x, dtype=float)
x_std = (x - x.mean()) / x.std()
print(x_std, x_std.mean(), x_std.std())


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356] 0.0 0.9999999999999999


# 11. Conversão de tipos (fácil)

In [ ]:

import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
a_f32 = a.astype(np.float32)
a_i64 = a_f32.astype(np.int64)
print(a.dtype, a_f32.dtype, a_i64.dtype)


int32 float32 int64


# 12. Clipping (fácil)

In [ ]:

import numpy as np

a = np.array([2, 5, 7, 1, 9])
clipped = np.clip(a, 0, 5)
print(clipped)


[2 5 5 1 5]


# 13. Inversão (fácil) — sem usar [::-1]

In [ ]:

import numpy as np

v = np.arange(10)
v_inv = np.flip(v)
print(v_inv)


[9 8 7 6 5 4 3 2 1 0]


# 14. Empilhamento (fácil)


In [ ]:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h = np.hstack((a, b))
v = np.vstack((a, b))
print(h)
print(v)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# 15. Diagonal (fácil)


In [ ]:

import numpy as np

M = np.diag(np.full(4, 5))
print(M)


[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


# 16. Somas por eixo (fácil)


In [ ]:

import numpy as np

A = np.arange(12).reshape(3, 4)
soma_linhas = A.sum(axis=1)
soma_colunas = A.sum(axis=0)
print("linhas:", soma_linhas)
print("colunas:", soma_colunas)


linhas: [ 6 22 38]
colunas: [12 15 18 21]


# 17. Frequências inteiras (fácil)



In [ ]:

import numpy as np

rng = np.random.default_rng(42)
vals = rng.integers(0, 10, size=100)
freq = np.bincount(vals, minlength=10)
print(freq)


[ 9  9  6  9 15  7 11 15 12  7]


# 18. Slicing com passo (fácil)


In [ ]:

import numpy as np

v = np.arange(20)
sel = v[1::3]
print(sel)


[ 1  4  7 10 13 16 19]


# 19. Máscara booleana (fácil)


In [ ]:

import numpy as np

v = np.arange(20)
mask = (v % 2 == 0)
pares = v[mask]
print(mask)
print(pares)


[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 0  2  4  6  8 10 12 14 16 18]


# 20. Lista de listas → array (fácil)


In [ ]:

import numpy as np

L = [[1, 2, 3], [4, 5, 6]]
arr = np.array(L)
print(arr)
print("shape:", arr.shape, "dtype:", arr.dtype)


[[1 2 3]
 [4 5 6]]
shape: (2, 3) dtype: int64


# 21. Datas básicas (fácil)


In [ ]:

import numpy as np

datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(datas)


['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


# 22. Centralizar colunas (fácil)


In [ ]:

import numpy as np

A = np.array([[1., 2., 3.],
              [4., 5., 6.]])
A_centered = A - A.mean(axis=0, keepdims=True)
print(A_centered)


[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


# 23. Produto elemento-a-elemento vs. escalar (fácil)


In [ ]:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

elem = a * b
dot1 = np.dot(a, b)
dot2 = a @ b
print(elem, dot1, dot2)


[ 4 10 18] 32 32


# 24. Troca de colunas (fácil)



In [ ]:

import numpy as np

A = np.arange(12).reshape(3, 4)
tmp = A[:, 0].copy()
A[:, 0] = A[:, 2]
A[:, 2] = tmp
print(A)



[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]
